/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_makeriga_tgbot_features_ping_PingFeature */

#ifndef _Included_org_makeriga_tgbot_features_ping_PingFeature
#define _Included_org_makeriga_tgbot_features_ping_PingFeature
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_makeriga_tgbot_features_ping_PingFeature
 * Method:    ping
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_makeriga_tgbot_features_ping_PingFeature_ping
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
